image: gradle:8.11.1

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - gradle
            script:
              - gradle build
            after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
  branches:
    main:
      - step:
          name: Deploy to Fly.io
          image: golang:1.15
          deployment: production
          script:
            - apt-get update -qq && apt-get install -y curl tree python3
            - python3 copy_secrets.py
            - curl -L https://fly.io/install.sh | sh
            - export FLYCTL_INSTALL="/root/.fly"
            - export PATH="$FLYCTL_INSTALL/bin:$PATH"
            - flyctl deploy